### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'seconds_per_goal_forfeit'

### ISSUE THREAD

**Issue by OGMatrix** [Rolv-Arild/rocket-learn#47]
EVALUATION GAME
╭─────────────────────────────┬───────────┬──────────────────────────┬───────────╮
│ Blue                        │ rating    │ Orange                   │ rating    │
├─────────────────────────────┼───────────┼──────────────────────────┼───────────┤
│ Bot-v0-deterministic │ 0.00±2.00 │Bot-v0-stochastic │ 0.00±2.00 │
╰─────────────────────────────┴───────────┴──────────────────────────┴───────────╯
0 steps [00:00, ? steps/s]Traceback (most recent call last):
  File "D:\rocket-learn\examples\default\worker.py", line 66, in <module>
    RedisRolloutWorker(r, "MrBean_BOT", match,
  File "D:\rocket-learn\rocket_learn2\rollout_generator\redis\redis_rollout_worker.py", line 362, in run
    result = rocket_learn2.utils.generate_episode.generate_episode(self.env, agents, evaluate=True,
  File "D:\rocket-learn\rocket_learn2\utils\generate_episode.py", line 31, in generate_episode
    game_condition = GameCondition(tick_skip=env._match._tick_skip,  # noqa
TypeError: __init__() got an unexpected keyword argument 'seconds_per_goal_forfeit'

**Comment by Kaiyotech** [comment]
I suspect you might be using a rocket learn example with rocket learn v2.

**Comment by OGMatrix** [comment]
> I suspect you might be using a rocket learn example with rocket learn v2.

Nah, I just renamed the file. I suspect that it might struggles with deterministic and stochastic at opposite teams at the same time. I just fixed it using a try/catch between it. And I also forked it today so yea
